### PR TITLE
Fix code to support Django 4 and up, edge case for code older than 3.2

### PR DESCRIPTION
**Pull request by c-goosen**
Past django 3.2 there was a breaking change in the middleware I fixed before, but forgot to account for newer version in logic. This should be the required fix for that

### CODE REVIEW

**Comment by c-goosen** [comment]
@shanx

**Comment by shanx** [comment]
Hi @c-goosen thanks for the PR! @bashu took over maintenance for this library. @bashu do you have time to look into this?

**Comment by c-goosen** [comment]
Thank you both, appreciate the effort

**Comment by shanx** [comment]
Thanks for the improvement!!

**Pull request merged**
